server:
  port: 8080
spring:
  application:
    name: "FirstChallenge"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

routes:
  paths:
    users: "/api/v1/usuarios"
    usersById: "/api/v1/usuarios/{id}"

adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "userdb"
    schema: "public"
    username: "postgres"
    password: "password"

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.tuempresa: DEBUG   # tu paquete principal
  file:
    name: logs/app.log